[package]
name = "sockies"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.68"
bytemuck = "1.12.3"
byteorder = "1.4.3"
crc = "3.0.0"
num-derive = "0.3.3"
num-traits = "0.2.15"
